[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = ["pip3.12 install -r requirements.txt"]

[phases.build]
cmds = ["python3.12 manage.py collectstatic --noinput"]

[start]
cmd = "python3.12 manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"